networks:
  dtupay_internal:
    name: dtupay_internal
    driver: bridge

services:
  account_service:
    build: ./account_service
    image: account_service
    container_name: account_service
    ports:
      - "8080:8080"
    networks:
      - dtupay_internal

  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq
    networks:
      - dtupay_internal
    ports:
    - "5672:5672"
    - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      retries: 10