networks:
  dtupay_internal:
    name: dtupay_internal
    driver: bridge

services:
  facade_service:
    build: ./facade_service
    image: facade_service
    container_name: facade_service
    ports:
      - "8080:8080"
    networks:
      - dtupay_internal
  
  payment_service:
    build: ./payment_service
    image: payment_service
    container_name: payment_service
    networks:
      - dtupay_internal
      
  account_service:
    build: ./account_service
    image: account_service
    container_name: account_service
    networks:
      - dtupay_internal

  reporting_service:
    build: ./reporting_service
    image: reporting_service
    container_name: reporting_service
    networks:
      - dtupay_internal

  token_manager_service:
    build: ./token_manager_service
    image: token_manager_service
    container_name: token_manager_service
    networks:
      - dtupay_internal

  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq
    networks:
      - dtupay_internal
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      retries: 10