networks:
  dtupay_internal:
    name: dtupay_internal
    driver: bridge

services:
  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq
    networks:
      - dtupay_internal
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s  # Added: wait 30s before starting health checks

  token_manager_service:
    build: ./token_manager_service
    image: token_manager_service
    container_name: token_manager_service
    networks:
      - dtupay_internal
    depends_on:
      rabbitmq:
        condition: service_healthy