networks:
  dtupay_internal:
    name: dtupay_internal
    driver: bridge

services:
  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - dtupay_internal
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "check_port_connectivity"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  token_manager_service:
    build: ./token_manager_service
    image: token_manager_service
    container_name: token_manager_service
    networks:
      - dtupay_internal
    depends_on:
      rabbitmq:
        condition: service_healthy

  facade_service:
    build: ./facade_service
    image: facade_service
    ports:
      - "8080:8080"
    networks:
      - dtupay_internal
    depends_on:
      rabbitmq:
        condition: service_healthy  # Wait for health check to pass

  payment_service:
    build: ./payment_service
    image: payment_service
    container_name: payment_service
    networks:
      - dtupay_internal
    depends_on:
      rabbitmq:
        condition: service_healthy

  account_service:
    build: ./account_service
    image: account_service
    container_name: account_service
    networks:
      - dtupay_internal
    depends_on:
      rabbitmq:
        condition: service_healthy
